######################################################################
##
## Filename: Comparador_3outs_tb.udo
## Created on: Sun Jan 12 18:41:59 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
