######################################################################
##
## Filename: Comparador_3outs.udo
## Created on: Wed Jan 15 4:13:55 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
