######################################################################
##
## Filename: Comprobador_tb.udo
## Created on: Mon Jan 13 12:45:32 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
