######################################################################
##
## Filename: Restador_tb.udo
## Created on: Mon Jan 13 13:49:40 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
