######################################################################
##
## Filename: Sumador_tb.udo
## Created on: Tue Jan 14 16:43:59 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
