######################################################################
##
## Filename: Top_Expendedora_tb.udo
## Created on: Wed Jan 15 1:03:34 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
